import { defineCollection, z } from "astro:content";
import { glob } from "astro/loaders";

const blog = defineCollection({
  loader: glob({ pattern: "**/*.md", base: "./src/content/blog" }),
  schema: z.object({
    title: z.string(),
    subtitle: z.string().optional(),
    description: z.string(),
    pubDate: z.coerce.date(),
    author: z.string(),
    organization: z.string().default("MLKFS"),
    // Social card. Defaults to /og/blog/<id>.png, generated by `npm run og`.
    image: z.string().optional(),
  }),
});

export const collections = { blog };
